/** 与后端 CacheCode 保持一致（value 常量）；展示文案从全局字典 store 读取 */

export const CacheCode = {
  TEAM_STATUS: 'team_status',
  TEAM_STATUS_NORMAL: 'NORMAL',
  TEAM_STATUS_PENDING_TOPIC: 'PENDING_TOPIC',
  TEAM_STATUS_TOPIC_REJECTED: 'TOPIC_REJECTED',
  TEAM_STATUS_UNLOCKED: 'UNLOCKED',

  MEMBER_STATUS: 'member_status',
  MEMBER_STATUS_ACTIVE: 'ACTIVE',
  MEMBER_STATUS_LEFT: 'LEFT',

  APPROVAL_STATUS: 'approval_status',
  APPROVAL_STATUS_PENDING: 'PENDING',
  APPROVAL_STATUS_APPROVED: 'APPROVED',
  APPROVAL_STATUS_REJECTED: 'REJECTED',

  PLAN_TASK_STATUS: 'plan_task_status',
  PLAN_TASK_STATUS_NOT_STARTED: 'NOT_STARTED',
  PLAN_TASK_STATUS_IN_PROGRESS: 'IN_PROGRESS',
  PLAN_TASK_STATUS_COMPLETED: 'COMPLETED',
  PLAN_TASK_STATUS_CANCELLED: 'CANCELLED',

  WEEKLY_REPORT_STATUS: 'weekly_report_status',
  WEEKLY_REPORT_STATUS_DRAFT: 'DRAFT',
  WEEKLY_REPORT_STATUS_SUBMITTED: 'SUBMITTED',

  USER_ROLE: 'user_role',
  USER_ROLE_TEACHER: 'TEACHER',
  USER_ROLE_STUDENT: 'STUDENT',

  WORKSPACE_NODE_TYPE: 'workspace_node_type',
  WORKSPACE_NODE_TYPE_FOLDER: 'FOLDER',
  WORKSPACE_NODE_TYPE_DOCUMENT: 'DOCUMENT',
}

/** 计划任务状态 value */
export const PLAN_TASK_STATUS = {
  NOT_STARTED: CacheCode.PLAN_TASK_STATUS_NOT_STARTED,
  IN_PROGRESS: CacheCode.PLAN_TASK_STATUS_IN_PROGRESS,
  COMPLETED: CacheCode.PLAN_TASK_STATUS_COMPLETED,
  CANCELLED: CacheCode.PLAN_TASK_STATUS_CANCELLED,
}

/** 周报状态 value */
export const WEEKLY_REPORT_STATUS = {
  DRAFT: CacheCode.WEEKLY_REPORT_STATUS_DRAFT,
  SUBMITTED: CacheCode.WEEKLY_REPORT_STATUS_SUBMITTED,
}
