/** 与后端 CacheCode 保持一致（value 常量）；展示文案从全局字典 store 读取 */

export const CacheCode = {
  TEAM_STATUS: 'team_status',
  TEAM_STATUS_NORMAL: 'NORMAL',
  TEAM_STATUS_PENDING_TOPIC: 'PENDING_TOPIC',
  TEAM_STATUS_TOPIC_REJECTED: 'TOPIC_REJECTED',
  TEAM_STATUS_UNLOCKED: 'UNLOCKED',

  MEMBER_STATUS: 'member_status',
  MEMBER_STATUS_ACTIVE: 'ACTIVE',
  MEMBER_STATUS_LEFT: 'LEFT',

  APPROVAL_STATUS: 'approval_status',
  APPROVAL_STATUS_PENDING: 'PENDING',
  APPROVAL_STATUS_APPROVED: 'APPROVED',
  APPROVAL_STATUS_REJECTED: 'REJECTED',

  PLAN_TASK_STATUS: 'plan_task_status',
  PLAN_TASK_STATUS_NOT_STARTED: 'NOT_STARTED',
  PLAN_TASK_STATUS_IN_PROGRESS: 'IN_PROGRESS',
  PLAN_TASK_STATUS_COMPLETED: 'COMPLETED',
  PLAN_TASK_STATUS_CANCELLED: 'CANCELLED',

  WEEKLY_REPORT_STATUS: 'weekly_report_status',
  WEEKLY_REPORT_STATUS_DRAFT: 'DRAFT',
  WEEKLY_REPORT_STATUS_SUBMITTED: 'SUBMITTED',

  USER_ROLE: 'user_role',
  USER_ROLE_STUDENT: 'STUDENT',
  USER_ROLE_TEACHER: 'TEACHER',
  USER_ROLE_ADMIN: 'ADMIN',

  DATA_SCOPE: 'data_scope',
  DATA_SCOPE_SELF: 'SELF',
  DATA_SCOPE_COURSE: 'COURSE',
  DATA_SCOPE_ALL: 'ALL',

  SYS_STATUS: 'sys_status',
  SYS_STATUS_ACTIVE: 'ACTIVE',
  SYS_STATUS_DISABLED: 'DISABLED',

  MENU_TYPE: 'menu_type',
  MENU_TYPE_DIR: 'M',
  MENU_TYPE_MENU: 'C',
  MENU_TYPE_BUTTON: 'F',

  ROUTE_MATCH: 'route_match',
  ROUTE_MATCH_EXACT: 'EXACT',
  ROUTE_MATCH_PREFIX: 'PREFIX',

  MENU_VISIBLE: 'menu_visible',
  MENU_VISIBLE_SHOW: 'SHOW',
  MENU_VISIBLE_HIDE: 'HIDE',

  HTTP_METHOD: 'http_method',
  HTTP_METHOD_GET: 'GET',
  HTTP_METHOD_POST: 'POST',
  HTTP_METHOD_PUT: 'PUT',
  HTTP_METHOD_DELETE: 'DELETE',
  HTTP_METHOD_PATCH: 'PATCH',

  WORKSPACE_NODE_TYPE: 'workspace_node_type',
  WORKSPACE_NODE_TYPE_FOLDER: 'FOLDER',
  WORKSPACE_NODE_TYPE_DOCUMENT: 'DOCUMENT',
  WORKSPACE_NODE_TYPE_SHEET: 'SHEET',

  COURSE_STATUS: 'course_status',
  COURSE_STATUS_DRAFT: 'DRAFT',
  COURSE_STATUS_ACTIVE: 'ACTIVE',
  COURSE_STATUS_ARCHIVED: 'ARCHIVED',

  TERM_SEASON: 'term_season',
  TERM_SEASON_SPRING: 'SPRING',
  TERM_SEASON_SUMMER: 'SUMMER',
  TERM_SEASON_AUTUMN: 'AUTUMN',
  TERM_SEASON_WINTER: 'WINTER',

  ENROLL_STATUS: 'enroll_status',
  ENROLL_STATUS_ENROLLED: 'ENROLLED',
  ENROLL_STATUS_DROPPED: 'DROPPED',

  STUDENT_MILESTONE_STATUS: 'student_milestone_status',
  STUDENT_MILESTONE_NEED_ENROLL: 'NEED_ENROLL',
  STUDENT_MILESTONE_NEED_TEAM: 'NEED_TEAM',
  STUDENT_MILESTONE_NEED_TOPIC: 'NEED_TOPIC',
  STUDENT_MILESTONE_TOPIC_PENDING: 'TOPIC_PENDING',
  STUDENT_MILESTONE_TOPIC_REJECTED: 'TOPIC_REJECTED',
  STUDENT_MILESTONE_READY: 'READY',
}

/** 计划任务状态 value */
export const PLAN_TASK_STATUS = {
  NOT_STARTED: CacheCode.PLAN_TASK_STATUS_NOT_STARTED,
  IN_PROGRESS: CacheCode.PLAN_TASK_STATUS_IN_PROGRESS,
  COMPLETED: CacheCode.PLAN_TASK_STATUS_COMPLETED,
  CANCELLED: CacheCode.PLAN_TASK_STATUS_CANCELLED,
}

/** 周报状态 value */
export const WEEKLY_REPORT_STATUS = {
  DRAFT: CacheCode.WEEKLY_REPORT_STATUS_DRAFT,
  SUBMITTED: CacheCode.WEEKLY_REPORT_STATUS_SUBMITTED,
}
